sudo: required
service:
  - docker

before_install:
  - docker run -e CI=true zalajobi/react-test npm test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zalajobi/react-test npm test

after_success:
  - docker build -t zalajobi/multi-client ./client
  - docker build -t zalajobi/multi-server ./server
  - docker build -t zalajobi/multi-nginx ./nginx
  - docker build -t zalajobi/multi-worker ./worker

# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push image to docker
  - docker push zalajobi/multi-client
  - docker push zalajobi/multi-nginx
  - docker push zalajobi/multi-server
  - docker push zalajobi/multi-worker


  # DOCKER_USERNAME
  # DOCKER_PASSWORD